// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"time"
)

type User struct {
	ID                int32     `json:"id"`
	Name              string    `json:"name"`
	PhoneNumber       string    `json:"phone_number"`
	Otp               string    `json:"otp"`
	OtpExpirationTime time.Time `json:"otp_expiration_time"`
}
